Repository Jeans-ssu/Kiri, pull requests merged in 2022-12, with the labels that each got.

#4 Feat/footer
  client/kiri/package-lock.json
  client/kiri/package.json
  client/kiri/public/index.html
  client/kiri/public/kiri_logo.png
  client/kiri/public/logo192.png
  client/kiri/public/logo512.png
  client/kiri/public/manifest.json
  client/kiri/public/robots.txt
  client/kiri/src/App.css
  client/kiri/src/App.js
  client/kiri/src/App.test.js
  client/kiri/src/components/Footer.js
  client/kiri/src/index.css
  client/kiri/src/index.js
  client/kiri/src/logo.svg
  client/kiri/src/reportWebVitals.js
  client/kiri/src/setupTests.js
Labels: Client

#5 Feat/header
  client/kiri/package-lock.json
  client/kiri/package.json
  client/kiri/src/components/Header.js
Labels: Front

#12 [FE] Eslint/Prettier 적용, Button 컴포넌트 생성
  client/kiri/.eslintignore
  client/kiri/.eslintrc.json
  client/kiri/.prettierignore
  client/kiri/.prettierrc.json
  client/kiri/package-lock.json
  client/kiri/package.json
  client/kiri/src/Components/Buttons.js
  client/kiri/src/Components/Footer.js
  client/kiri/src/containers/PageContainer.js
  client/kiri/src/styles/theme.js
Labels: Front

#16 [FE] 메인페이지 캐러셀 구현
  client/kiri/package-lock.json
  client/kiri/package.json
  client/kiri/public/img/event_cover.jpeg
  client/kiri/src/Components/Footer.js
  client/kiri/src/components/Header.js
  client/kiri/src/containers/PageContainer.js
  client/kiri/src/pages/Main/MainCarousel.js
  client/kiri/src/pages/Main/MainPage.js
Labels: Front

#18 [FE] 메인페이지 UI 대략적으로 구현 완료
  client/kiri/src/Components/Footer.js
  client/kiri/src/components/Header.js
  client/kiri/src/containers/PageContainer.js
  client/kiri/src/pages/Main/BestEvents.js
  client/kiri/src/pages/Main/MainCarousel.js
  client/kiri/src/pages/Main/MainEvents.js
  client/kiri/src/pages/Main/MainPage.js
  client/kiri/src/pages/Main/SelectedEvents.js
Labels: Front

#19 [FE] 회원가입 페이지 1차 구현
  client/kiri/src/App.js
  client/kiri/src/components/Header.js
  client/kiri/src/pages/Signup/SignupInputs.js
  client/kiri/src/pages/Signup/SignupPage.js
Labels: Front

#15 ✨ [FE] feat: event field page
  client/kiri/data.json
  client/kiri/public/poster.jpg
  client/kiri/src/App.js
  client/kiri/src/pages/Event/EventFieldPage.js
  client/kiri/src/pages/Event/EventKeyworldPage.js
Labels: Front

#23 [FE] proxy 에러 수정, 회원가입 UI 수정
  client/kiri/src/pages/Signup/SignupInputs.js
  client/kiri/src/setupProxy.js
  client/kiri/src/styles/theme.js
Labels: Front

#24 [FE] 마이페이지
  client/kiri/src/App.js
  client/kiri/src/components/Header.js
  client/kiri/src/containers/PageContainer.js
  client/kiri/src/pages/Mypage/Mypage.js
  client/kiri/src/pages/Mypage/MypageInput.js
  client/kiri/src/pages/Mypage/MypageInputs.js
  client/kiri/src/pages/Mypage/Withdraw.js
  client/kiri/src/pages/Signin/SigninPage.js
  client/kiri/src/pages/Signup/SignupInputs.js
  client/kiri/src/pages/Signup/SignupPage.js
Labels: Front

#25 [FE] 마이페이지, 로그인, 회원가입 페이지 추가 기능
  client/kiri/src/pages/Mypage/Mypage.js
  client/kiri/src/pages/Mypage/MypageInput.js
  client/kiri/src/pages/Signin/SigninInputs.js
  client/kiri/src/pages/Signin/SigninPage.js
  client/kiri/src/pages/Signup/SignupInputs.js
  client/kiri/src/pages/Signup/SignupPage.js
Labels: Front

#27 Feat/header
  client/kiri/src/components/Header.js
Labels: Front

#26 Feat/event info page 완성
  client/kiri/src/App.js
  client/kiri/src/pages/Event/EventInfoPage.js
Labels: Front

#29 Feat/header [FE] style: 검색창 디자인 수정
  client/kiri/src/components/Header.js
Labels: Front

#30 [FE] 테스트
  client/kiri/src/pages/Signin/SigninInputs.js
Labels: Back

#31 [FE] 회원가입, 로그인, 마이페이지 유효성 검사 및 필드 수정
  client/kiri/src/pages/Mypage/MypageInput.js
  client/kiri/src/pages/Mypage/MypageInputs.js
  client/kiri/src/pages/Signin/SigninInputs.js
  client/kiri/src/pages/Signup/SignupInputs.js
Labels: Front
